#!/usr/bin/env python
# coding: utf8

from twitter import *
import sys

access_token = "access_token"
access_token_secret = "access_token_secret"
consumer_key = "consumer_key"
consumer_secret = "consumer_secret"

t = Twitter(auth=OAuth(access_token, access_token_secret, consumer_key, consumer_secret))

try: 
    sys.argv[1]
except IndexError: 
    print('Epty tweet text. Run script with 1 arg.')
    sys.exit()
else:
	t.statuses.update(status=sys.argv[1])
	print('Tweet "'+sys.argv[1]+'" was published.')